### ISSUE TITLE
Can't see files and folders in my S3 bucket

### ISSUE THREAD

**Issue by jensbaumgart** [iterate-ch/cyberduck#12635]
I successfully connected to my amazon S3 bucket. But I can't see the contained files and folders.
I can create files and folders in the bucket. See attached screenshot.

Cyberduck Version 8.1.1 (36550)
macOS 12.0.1 (21A559)
<img width="692" alt="cyberduck" src="https://user-images.githubusercontent.com/498012/145226601-71fa5bf4-b6ff-49e5-a608-7c433e6de5c5.png">

**Comment by fishcharlie** [comment]
@jensbaumgart Do you have the correct IAM roles/permissions setup?

**Comment by edwinv** [comment]
I'm experiencing the same issue. The S3 bucket and IAM policy have been in place since 2018. I was always able to list and update files. With the last version of Cyberduck, listing of subfolders in the bucket suddenly throws this error: 

<img width="312" alt="CleanShot 2021-12-12 at 17 23 18@2x" src="https://user-images.githubusercontent.com/563294/145720508-d468eb88-4384-435c-a287-5060621105e2.png">

I've reconfirmed the policy by using the AWS cli tool, this lists the bucket contents without issues. This confirms for me a possible bug in Cyberduck.

Related: #12596, #11883, #11896

**Comment by jensbaumgart** [comment]
The bucket is an external bucket. How to connect to an external bucket? I tried to put the bucket name in front of the server name, but this did not help. I still do not see the content of /

**Comment by dkocher** [comment]
Please do not set a region specific endpoint for the hostname. Refer to [Access single bucket](https://docs.cyberduck.io/protocols/s3/#access-single-bucket).

**Comment by jensbaumgart** [comment]
I put the bucket name in front of the server name. With this, I get the same result.
Then I entered the bucket name in the path field of the bookmark. This results in error message "Cannot read bucket location"
My colleagues using S3 Browser on Windows can access the bucket using "Add external bucket".

**Comment by jensbaumgart** [comment]
if I use S3 REST API, I see all objects in the bucket (jbtest and others not shown in Cyberduck):
https://s3-eu-central-1.amazonaws.com/hcp-XXXXXXXXXXXXXXXXXXXX?list-type=2

**Comment by dkocher** [comment]
Make sure your IAM policy allows `s3:GetBucketLocation`.

**Comment by jensbaumgart** [comment]
I have no access to these settings. I only have access key, secret key and bucket name.

**Comment by dkocher** [comment]
This is possibly fixed with #12694. Please try the latest snapshot build _8.2.0.36660_.

**Comment by jensbaumgart** [comment]
Can't find download for 8.2.0.36660. Can you provide a link?

**Comment by dkocher** [comment]
See [Preferences → Update](https://docs.cyberduck.io/cyberduck/preferences/#snapshot-builds) or https://update.cyberduck.io/nightly/

**Comment by jensbaumgart** [comment]
The issue persists with version Version 8.2.0 (36663)
Tried all combinations: 
put bucket in path: yes/no 
put bucket in server name: yes/no

**Comment by dkocher** [comment]
Please provide [logging output](https://docs.cyberduck.io/cyberduck/support/#logging-output) with _Debug_ option enabled.

**Comment by jensbaumgart** [comment]
[cyberduck copy.log](https://github.com/iterate-ch/cyberduck/files/7770268/cyberduck.copy.log)

**Comment by jensbaumgart** [comment]
We finally found the issue: our paths contained a //. After removing the //, everything works fine.
