### ISSUE TITLE
Support for Dark Mode is missing

### ISSUE THREAD

**Issue by dcblack** [iterate-ch/cyberduck#13510]
Dark mode is now present on most platforms (Windows, Mac, Linux) as an option and very often chosen to reduce fatigue. Cyberduck lacks support for this.

**Comment by AliveDevil** [comment]
We are aware of this, but this is a fundamental underlying framework issue on Windows, which won‘t be addressed by Microsoft.
See #13036 for steps required to get this rolling.

**Comment by Tampa** [comment]
You say this is a WinForms issue, but that already supports color palettes and ways to change both background and text colors. There are even projects like DarkUI that aim to make this easier by providing a way to create dark versions of all forms automatically from the Forms in an existing project. Could you elaborate more as to why this isn't possible or what kind of work is needed to create dark copies of the current forms?

**Comment by ashauryn** [comment]
I have been using cyberduck for a year but am planning to move away because of the lack of support for this feature.

**Comment by l4kr** [comment]
I achieved dark mode with MicaForEveryone, there's no reason Cyberduck can't just integrate it. Nanazip did it.

**Comment by Beats24-7** [comment]
So has this been fixed? I still don't see any option to switch to dark mode.
